# This file was generated by GoReleaser. DO NOT EDIT.
cask "tolvi" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "e62617de0cc2170e84983dc836b8149ff9c84c40fd68336eaf1c3ba81ac15019"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "6117ee62218cc902e53606d36a3b0aff5d879944c347373aafbf16473611a922"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "94507c9cb54f3e17f7cdf2f2f1966d8cbab249602600349958163ea75856caa2"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c995b20241197efbcf197d216906a2feb3b221b28e3289bf97c9d68473cde4d"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tolvi"
  desc "Engineering knowledge vault CLI — capture decisions, sessions, and patterns as Markdown."
  homepage "https://tolvilabs.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tolvi"

  # No zap stanza required

end
