# This file was generated by GoReleaser. DO NOT EDIT.
cask "tolvi" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "b95bdbbc4b24e1e8da6260a2d9d9aa3c983e16eeec705b6c128808b4b08a2475"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "4910a1d473d0a883d2e92ea9366cfb63672abe1426cb8c0bd503e48b2a56ca33"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41b26718e0edcc9778c872146652a315e206e101fbe2be3b74e87bcc20e4ea7c"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a88f202c98aad5bf53b5eb56704558698e141e9cb38819b4a93254cc7a58d259"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tolvi"
  desc "Engineering knowledge vault CLI — capture decisions, sessions, and patterns as Markdown."
  homepage "https://tolvilabs.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tolvi"

  # No zap stanza required
end
