# This file was generated by GoReleaser. DO NOT EDIT.
cask "tolvi" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "b54d85a7a4f7f5e99839ae4618262a9c50da5d3db11c7a70ffc68028c1d14c62"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "56547aaf8dda2f007125fe41d21639f54de1fd216f56a4704d7ed68799e0f97e"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b8358711f7b97f7754b502bc1a9c0ead3607566a234dd05876fc8a6c1fe988a8"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "05dc51bdbeffa99c42890fb9421210dac0424cd916137214fb1e687739fc0cd8"
      url "https://github.com/tolvi-labs/tolvi/releases/download/v#{version}/tolvi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tolvi"
  desc "Engineering knowledge vault CLI — capture decisions, sessions, and patterns as Markdown."
  homepage "https://tolvilabs.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tolvi"

  # No zap stanza required
end
